### ISSUE TITLE
Several support library views and view attributes expect theme colors that are ColorStateLists to be StateListDrawables

### ISSUE THREAD

**Issue by jeffdgr8** [negusoft/GreenMatter#6]
I filed a bug with AOSP (https://code.google.com/p/android/issues/detail?id=176262), as I believe this to be an issue with the support library. But so that you are aware, and may be able to workaround this, you are using ColorStateLists to override the values for "colorPrimary", "colorPrimaryDark" and "colorAccent" in Theme.Appcompat. Theme.Appcompat gets these values from Base.V7.Theme.AppCompat where they're defined as @color/primary_material_dark, @color/primary_dark_material_dark and @color/accent_material_dark, which are defined as regular <resource> <color> values with hex integer strings.

Having these colors defined as ColorStateLists works fine for the most part, except for when using several support library views or setting certain view attributes. The ones I found are using either android.support.design.widget.NavigationView or android.support.v7.widget.Toolbar or setting the attribute android:fitsSystemWindows="true" in android.support.v4.widget.DrawerLayout will all cause a crash similar to this:

06-08 11:14:52.863    2147-2147/my.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: my.app, PID: 2147
    java.lang.RuntimeException: Unable to start activity ComponentInfo{my.app/my.app.nav.MainActivity}: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v4.widget.DrawerLayout
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class android.support.v4.widget.DrawerLayout
            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at my.app.nav.MainActivity.onCreate(MainActivity.java:30)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at my.app.nav.MainActivity.onCreate(MainActivity.java:30)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.content.res.Resources$NotFoundException: File res/color/gm__primary_dark.xml from drawable resource ID #0x7f0e007e
            at android.content.res.Resources.loadDrawableForCookie(Resources.java:2479)
            at android.content.res.Resources.loadDrawable(Resources.java:2381)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
            at android.support.v4.widget.DrawerLayoutCompatApi21.getDefaultStatusBarBackground(DrawerLayoutCompatApi21.java:80)
            at android.support.v4.widget.DrawerLayout$DrawerLayoutCompatImplApi21.getDefaultStatusBarBackground(DrawerLayout.java:309)
            at android.support.v4.widget.DrawerLayout.<init>(DrawerLayout.java:362)
            at android.support.v4.widget.DrawerLayout.<init>(DrawerLayout.java:329)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at my.app.nav.MainActivity.onCreate(MainActivity.java:30)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'drawable' attribute or child tag defining a drawable
            at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:194)
            at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:127)
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1128)
            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1032)
            at android.content.res.Resources.loadDrawableForCookie(Resources.java:2469)
            at android.content.res.Resources.loadDrawable(Resources.java:2381)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:749)
            at android.support.v4.widget.DrawerLayoutCompatApi21.getDefaultStatusBarBackground(DrawerLayoutCompatApi21.java:80)
            at android.support.v4.widget.DrawerLayout$DrawerLayoutCompatImplApi21.getDefaultStatusBarBackground(DrawerLayout.java:309)
            at android.support.v4.widget.DrawerLayout.<init>(DrawerLayout.java:362)
            at android.support.v4.widget.DrawerLayout.<init>(DrawerLayout.java:329)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
            at android.view.LayoutInflater.createView(LayoutInflater.java:607)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:482)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at my.app.nav.MainActivity.onCreate(MainActivity.java:30)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

I attempted to modify the GreenMatter library theme to use StateListDrawables instead of ColorStateLists and just got this crash:

06-08 11:09:50.161    1098-1098/my.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: my.app, PID: 1098
    java.lang.RuntimeException: Unable to start activity ComponentInfo{my.app/my.app.nav.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/gm__primary_dark.xml from color state list resource ID #0x7f02008a
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/gm__primary_dark.xml from color state list resource ID #0x7f02008a
            at android.content.res.Resources.loadColorStateList(Resources.java:2592)
            at android.content.res.TypedArray.getColor(TypedArray.java:395)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3477)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3677)
            at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1943)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:148)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
            at my.app.BaseActivity.onCreate(BaseActivity.java:26)
            at my.app.nav.MainActivity.onCreate(MainActivity.java:29)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #18: <item> tag requires a 'android:color' attribute.
            at android.content.res.ColorStateList.inflate(ColorStateList.java:230)
            at android.content.res.ColorStateList.createFromXmlInner(ColorStateList.java:152)
            at android.content.res.ColorStateList.createFromXml(ColorStateList.java:131)
            at android.content.res.Resources.loadColorStateList(Resources.java:2588)
            at android.content.res.TypedArray.getColor(TypedArray.java:395)
            at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3477)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3677)
            at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1943)
            at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:148)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
            at my.app.BaseActivity.onCreate(BaseActivity.java:26)
            at my.app.nav.MainActivity.onCreate(MainActivity.java:29)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

So neither using StateListDrawables or ColorStateLists will satisfy all the views' expectations. But it seems most work fine with ColorStateLists, as removing the android.support.design.widget.NavigationViev, android.support.v7.widget.Toolbar and android:fitsSystemWindows="true" attribute from android.support.v4.widget.DrawerLayout in my layout allows the views to inflate properly and everything works fine in this configuration, not using these UI components.

Since these support library views are integral pieces of modern material design apps, hopefully there is a workable solution to getting them to work with GreenMatter.

**Comment by jeffdgr8** [comment]
AOSP comment on the bug report is: "These attributes must be raw colors, not CSLs. Please contact the library developer." Closed as working as intended.

So this is going to be a requirement for GreenMatter to define those colors as <resources> <color> in XML.

**Comment by blurkidi** [comment]
I am not surprised, actually. The method used by GreenMatter is somehow
"hack-ish", since themes are meant to be immutable. On top of that, the
mechanism to override colours doesn't work on Android M anymore, so the
functionality to override colors at runtime will dropped most probably.
(Yes, sad news).

The new objective for the library will be to serve as an enhancement to the
Support Library to backport the material theme, with minimum effort.

Thanks for your support. Cheers

**Comment by jeffdgr8** [comment]
Sad news indeed. Programmatic changing of theme colors is a big requirement in my app. Without being able to modify the theme, I'll have to resort to choosing from a selection of predefined themes, which won't be as flexible for our users. Thanks for your work on this library.
